#!/usr/bin/env bash
# Initialize a counter variable
counter=0

# Using a while loop to display "Best School" 10 times
while [ $counter -lt 10 ]
do
    if [ $counter -eq 3 ]
    then
	    echo "bad luck"
    elif [ $counter -eq 7 ]
    then
            echo "good luck"
    else
	    echo "Best School"
    fi
    # Increment the counter
    ((counter++))
done
