#!/usr/bin/env bash
# Loop for 12 hours
hour=0
minute=1

while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    
    minute=1
    # Loop for 59 minutes
    while [ $minute -le 59 ]
    do
        echo "$minute"
	((minute++))
    done
    ((hour++))
done
