#!/usr/bin/env bash
# configures the /etc/hosts file
# resolves localhost to 127.0.0.2
# resolves facebook to 8.8.8.8

sudo cp /etc/hosts ~/hosts.new
sed 's/127.0.0.1/127.0.0.2/g' ~/hosts.new > new
echo "8.8.8.8	facebook.com" >> new
sudo cp -f new /etc/hosts
