#!/usr/bin/env bash
#Bash script that displays all active IPv4 IPs on the machine it’s executed on.

# Use the ip command to list all active interfaces, filter only IPv4 addresses, and extract the IP addresses
IP_ADDRESSES=$(ip -4 addr show | grep inet | awk '{print $2}' | cut -d '/' -f 1)

# Display the list of active IPv4 addresses
echo "$IP_ADDRESSES"
